# Generated by Django 5.2.6 on 2025-10-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_plato_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Breve descripción o eslogan del restaurante.', null=True),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='Código QR del menú público.', null=True, upload_to='qrcodes/'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='activo',
            field=models.BooleanField(default=True, help_text='Controla si el menú público está activo o no.'),
        ),
    ]
