# Generated by Django 5.2.6 on 2025-10-27 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_restaurante_descripcion_restaurante_qr_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('qr', 'Escaneo QR'), ('menu', 'Visita Menú'), ('plato', 'Detalle Plato')], default='menu', max_length=20)),
                ('plato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vistas', to='core.plato')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='core.restaurante')),
            ],
        ),
    ]
